day two groups and transactions
paulshaun-kdtk/Vet_Clinic_DB pull request #2
Opened 2023-10-12 14:34 UTC by paulshaun-kdtk

# Changes 

- implemented transactions and rollbacks
- queried table based on groups
- modified animals table to include a pk on the id field

## results screenshots:

![Screenshot (261)](https://github.com/paulshaun-kdtk/Vet_Clinic_DB/assets/123934813/0d0f7e5f-70a1-4af1-8d7c-dd4414099048)
![Screenshot (262)](https://github.com/paulshaun-kdtk/Vet_Clinic_DB/assets/123934813/f162f7b5-9d5f-4a74-8ef3-cd239ededeab)
![Screenshot (263)](https://github.com/paulshaun-kdtk/Vet_Clinic_DB/assets/123934813/660689ab-12e1-4aec-9a98-9a2d20be16de)
![Screenshot (260)](https://github.com/paulshaun-kdtk/Vet_Clinic_DB/assets/123934813/b3a8d79d-d6d3-447c-89e5-0c37879d628b)

2023-10-12 15:11 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @paulshaun-kdtk , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media3.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/> |

## Highlights

- [ ].. ✅ Good code
- [ ].. ✅ Clean commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 15:11 UTC, joskalenda commented on schema.sql
> +    species VARCHAR(255)
- [ ] Well, you are asked to add a column to a table, and you do but in an unprofessional way, we are expecting you to use appropriate to add something to a given table, try reading on the `ALTER` command and update your project with the new info you will gain

2023-10-13 07:54 UTC, Abenezer-Tilahun commented on schema.sql
> +    species VARCHAR(255)
Fixed.

2023-10-13 08:03 UTC, Abenezer-Tilahun approved these changes
Hi @paulshaun-kdtk 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow. 
✔️ Good job for Implemented Suggested changes.


## Optional suggestions 

- [ ] Kindly make sure that for each project activity Use descriptive commit messages - each commit should be small enough to describe it in one sentence. The commit message should be written in the imperative tense and capitalized and Add descriptive README file to your project with each section of the README file address the current project activity. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

2023-10-14 10:36 UTC, merged